### ISSUE TITLE
IMDB Fetch does not work

### ISSUE THREAD

**Issue by ketzaldev** [Saviq/VCD-Db#3]
Hi,

They changed something on IMDB, it's not possible anymore to get the information.

Regs
Ket

**Comment by bjoerns1983** [comment]
Is it still possible to get search results, or is the search also not working anymore?

**Comment by ketzaldev** [comment]
Search result is still OK.

Fix should be commited soon
Ket

**Comment by Saviq** [comment]
Fixed in a223d562
