### ISSUE TITLE
VCDFetch_imdb.php, Actors fetch is still not 100%

### ISSUE THREAD

**Issue by utitor** [Saviq/VCD-Db#5]
Take movie: "Cats & Dogs: The Revenge of Kitty Galore" 
It will only fetch for the last 4 actors from the imdb site, this is not happening to all movies, but seems to be increasing ! 

Thanks

**Comment by Saviq** [comment]
Fixed in 2343ae5b1a99091b5988558b19fe05f7113e6e38
