### ISSUE TITLE
Frindly URL for new sort in category

### ISSUE THREAD

**Issue by Horizak** [Saviq/VCD-Db#8]
Saviq if you want i can help ;)

Open file includes/schema/htaccess.txt
Find in line 9

RewriteRule ^category/([0-9]+)/([0-9]+)/([a-zA-Z\+]*)$ index.php?page=category&category_id=$1&batch=$2&viewmode=$3 [QSA]

Replace for

RewriteRule ^category/([0-9]+)/([0-9]+)/(img|text)$ index.php?page=category&category_id=$1&batch=$2&viewmode=$3 [QSA]
RewriteRule ^category/([0-9]+)/([0-9]+)/([^\?/]*)$ index.php?page=category&category_id=$1&batch=$2&sort=$3 [QSA]

///////////////////////////////////

Open file classes/VCDPage.php
Find in line 136

"'\?page=category&amp;category_id=([0-9]_)&amp;batch=([0-9]_)&amp;viewmode=(img|text)'",

Add after

"'\?page=category&amp;category_id=([0-9]_)&amp;batch=([0-9]_)&amp;sort=([a-zA-Z\-]*)'",

Find in line 164

'category/\1/\2/\3',

Duplicate this line

icate this line

**Comment by Saviq** [comment]
Could you please make that into a patch? Or better yet, send a pull request on github (http://help.github.com/pull-requests/)?

**Comment by Horizak** [comment]
Done :D
